esphome:
  name: garagentor
  platform: ESP8266         # To be changed according to the used board
  board: nodemcuv2

wifi:
  ssid: !secret ssid          # Replace either with your secret or your SSID name
  password: !secret wlan_pwd  # Replace either with your secret or with your password
  manual_ip:                  # if you want to use DHCP place a '#' in front of lines 9 to 12
    static_ip: 192.168.0.144
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  #use_address: 192.168.0.27 #used the flash over the air if DHCP was used in a first setup

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garagentor Fallback Hotspot"
    password: "7WHmKojbIpUk"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable over the air updates
ota:

switch:
  - platform: gpio
    pin: 
      number: D1                      # if you use other pins than D1 and D2 check the behavior of these pins during reboot of the ESP device
      inverted: True
    name: "Garage door Open Switch"
    id: open_switch
    on_turn_on:
      - delay: 250ms
      - switch.turn_off: open_switch
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 
      number: D2
      inverted: True
    name: "Garage door close Switch"
    id: close_switch
    on_turn_on:
      - delay: 250ms
      - switch.turn_off: close_switch
    restore_mode: ALWAYS_OFF
  - platform: restart
    name: "Garagentor Restart"
  - platform: shutdown
    name: "Garagentor Shutdown"
    
cover:
  - platform: template
    name: "Garagentor"
    open_action:
      # Cancel any previous action
      - switch.turn_off: close_switch
      # Turn the OPEN switch on briefly
      - switch.turn_on: open_switch
      - delay: 0.1s
      - switch.turn_off: open_switch
    close_action:
      - switch.turn_off: open_switch
      - switch.turn_on: close_switch
      - delay: 0.1s
      - switch.turn_off: close_switch
    stop_action:
      - switch.turn_off: close_switch
      - switch.turn_off: open_switch
    optimistic: true
    assumed_state: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Garagentor IP"
    ssid:
      name: "Garagentor SSID"
